# Generated by Django 4.0.6 on 2022-11-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaccion', models.CharField(blank=True, db_column='TRANSACCION', max_length=255, null=True)),
                ('codarticulo', models.FloatField(blank=True, db_column='CODARTICULO', null=True)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=255, null=True)),
                ('unidadestotal', models.FloatField(blank=True, db_column='UNIDADESTOTAL', null=True)),
                ('precio', models.FloatField(blank=True, db_column='PRECIO', null=True)),
            ],
            options={
                'db_table': 'VENTAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedents', models.CharField(blank=True, db_column='ANTECEDENTS', max_length=255, null=True)),
                ('consequents', models.CharField(blank=True, db_column='CONSEQUENTS', max_length=255, null=True)),
                ('confidence', models.FloatField(blank=True, db_column='CONFIDENCE', null=True)),
            ],
            options={
                'db_table': 'RECOMENDACIONES',
                'managed': True,
            },
        ),
    ]
