# Generated by Django 4.0.6 on 2022-11-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recomendaciones',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
