# Generated by Django 4.0.6 on 2022-07-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=12)),
                ('horario_apertura', models.TimeField(verbose_name='horario de apertura')),
                ('horario_cierre', models.TimeField(verbose_name='horario de cierre')),
            ],
        ),
    ]
