# Generated by Django 4.0.6 on 2022-07-29 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('ingredientes', models.CharField(max_length=200)),
                ('calorias', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=20)),
                ('stock', models.DecimalField(decimal_places=0, max_digits=20)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.restaurante')),
            ],
        ),
    ]
